### ISSUE TITLE
招聘

### ISSUE THREAD

**Issue by mngogo** [shetz163/gojuonzu#1]
你网上吵吵要上海找前端工作。可是 竟然联系方式不留。你让我这想招你的人，怎么找到你呢？
看到消息后联系我， 942698706@qq.com 注明应聘前端github的名字

**Comment by shetz163** [comment]
您好，简历在上周六时已经投进了邮箱里了，但是没有收到回音，很希望能知道我因为哪些方面的不足而被筛的，谢谢。

**Comment by mngogo** [comment]
谢谢来信。收到了。但是几次联系不到你啊。 QQ留言你也不回音。你直接联系我吧。我给你地址来办公室聊聊：） 除了网上这个作品，其他相关你认为你有兴趣要发挥的带过来
